server:
  port: 8989
spring:
  datasource:
    url: jdbc:sqlserver://172.17.143.11:1433;databaseName=TmsEPrd;encrypt=true;trustServerCertificate=true
    username: api_calls
    password: password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true